/* Generated By:JJTree&JavaCC: Do not edit this line. pingulangCompilerConstants.java */
package source;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface pingulangCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO_PROGRAMA = 4;
  /** RegularExpression Id. */
  int FIM_PROGRAMA = 5;
  /** RegularExpression Id. */
  int INICIO_BLOCO = 6;
  /** RegularExpression Id. */
  int FIM_BLOCO = 7;
  /** RegularExpression Id. */
  int PINGU = 8;
  /** RegularExpression Id. */
  int INT_TYPE = 9;
  /** RegularExpression Id. */
  int FLOAT_TYPE = 10;
  /** RegularExpression Id. */
  int BOOL_TYPE = 11;
  /** RegularExpression Id. */
  int CHAR_TYPE = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int INPUT = 21;
  /** RegularExpression Id. */
  int OP_RELACIONAL = 22;
  /** RegularExpression Id. */
  int OP_LOGICO = 23;
  /** RegularExpression Id. */
  int OP_ARITMETICO = 24;
  /** RegularExpression Id. */
  int OP_IGUAL = 25;
  /** RegularExpression Id. */
  int OP_AUMENTO = 26;
  /** RegularExpression Id. */
  int OP_DIMINUI = 27;
  /** RegularExpression Id. */
  int OP_MULTIPLICA = 28;
  /** RegularExpression Id. */
  int OP_DIVIDE = 29;
  /** RegularExpression Id. */
  int INTEIRO = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int CHAR = 32;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int ID = 34;
  /** RegularExpression Id. */
  int VIRGULA = 35;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 36;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"E LA VAMOS NOS\"",
    "\"ISSO EH TUDO P-PESSOAL\"",
    "\"{\"",
    "\"}\"",
    "\"PINGU\"",
    "\"IO\"",
    "\"FLORZINHA\"",
    "\"SID\"",
    "\"PENELOPE CHARMOSA\"",
    "\"A GENTE VAI VIVER\"",
    "\"A GENTE VAI MORRER\"",
    "\"SERIA\"",
    "\"OU SERA QUE NAO\"",
    "\"A EH REPETE\"",
    "\"FORCA G\"",
    "\"YABBA DABBA DOO\"",
    "\"MOSTLA\"",
    "\"ESCLEVE\"",
    "<OP_RELACIONAL>",
    "<OP_LOGICO>",
    "<OP_ARITMETICO>",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "<INTEIRO>",
    "<FLOAT>",
    "<CHAR>",
    "<STRING>",
    "<ID>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
  };

}
